[basic]
maxQueueSize = 0
queueFullPolicy = "BLOCK"
maxBlockTime_us = 16
maxDropCount = 40960
autoExpandMultiply = 4

[output]
logRootDir = "./logs"
toFile = true
toConsole = false
minLogLevel = 0

[performance]
enableAsyncConsole = true
consoleFlushInterval_ms = 50
fileFlushInterval_ms = 1000
consoleBatchSize = 512
fileBatchSize = 4096
consoleBufferSize_kb = 16
fileBufferSize_kb = 1024

[rotation]
maxLogFileSize = 9999999999
maxLogFileCount = 10

[http]
url = ""
endpoint = "/logs"
contentType = "application/json"
timeout_sec = 30
maxRetries = 3
batchSize = 100
bufferSize_kb = 64
enableCompression = false
enableAsync = true
toHttp = false
