[basic]
maxQueueSize = 81920
queueFullPolicy = "BLOCK"
maxBlockTime_us = 16
maxDropCount = 40960
autoExpandMultiply = 4

[output]
logRootDir = "./logs"
toFile = true
toConsole = false
minLogLevel = 0

[performance]
enableAsyncConsole = true
consoleFlushInterval_ms = 50
fileFlushInterval_ms = 100
consoleBatchSize = 512
fileBatchSize = 1024
consoleBufferSize_kb = 16
fileBufferSize_kb = 32

[rotation]
maxLogFileSize = 999999999
maxLogFileCount = 10
